### ISSUE TITLE
feature：账号下载资源的时候，是否可以把专栏对应的评论一起下载下来

### ISSUE THREAD

**Issue by springandme** [zkep/mygeektime#16]
有时候课程评论比正文更有营养，评论区冒出一些好的举一反三例子，希望下载资源的时候把相应的评论一起下载下来

**Comment by zkep** [comment]
> 有时候课程评论比正文更有营养，评论区冒出一些好的举一反三例子，希望下载资源的时候把相应的评论一起下载下来

👌 收到，最近安排一下

**Comment by zkep** [comment]
> > 有时候课程评论比正文更有营养，评论区冒出一些好的举一反三例子，希望下载资源的时候把相应的评论一起下载下来
> 
> 👌 收到，最近安排一下

已经支持评论展示了，可以使用最新的docker镜像

**Comment by springandme** [comment]
已经能看到文章的评论了，感谢大佬

![Image](https://github.com/user-attachments/assets/e6523c97-27b9-4a6b-999f-2d526a112bd7)

**Comment by springandme** [comment]
不过我在使用 VIP 账号，缓存资源的时候，出现了这个错误，json: cannot unmarshal string into Go struct field DowloadRequest.pid of type int64，

![Image](https://github.com/user-attachments/assets/f2692adc-a5b9-48a0-938b-3b27d1a983b6)

**Comment by zkep** [comment]
> 不过我在使用 VIP 账号，缓存资源的时候，出现了这个错误，json: cannot unmarshal string into Go struct field DowloadRequest.pid of type int64，

收到，我本地复现下

**Comment by springandme** [comment]
> 不过我在使用 VIP 账号，缓存资源的时候，出现了这个错误，json: cannot unmarshal string into Go struct field DowloadRequest.pid of type int64，
> 
> ![Image](https://github.com/user-attachments/assets/f2692adc-a5b9-48a0-938b-3b27d1a983b6)

我缓存的是专栏里面的每一小节的文档，是出现这个错误，直接缓存整个专栏，就没有这个错误

**Comment by zkep** [comment]
> > 不过我在使用 VIP 账号，缓存资源的时候，出现了这个错误，json: cannot unmarshal string into Go struct field DowloadRequest.pid of type int64，
> > ![Image](https://github.com/user-attachments/assets/f2692adc-a5b9-48a0-938b-3b27d1a983b6)
> 
> 我缓存的是专栏里面的每一小节的文档，是出现这个错误，直接缓存整个专栏，就没有这个错误

好的，我本地可以复现，马上修一下，你先整个课程缓存吧。章节缓存我修复发版本再回复你

**Comment by springandme** [comment]
OK， 谢谢大佬支持

还有就是一个需求，课程「**生成在线文档**」的时候，是否可以把文章评论也附带上去呢

![Image](https://github.com/user-attachments/assets/38423fa6-212a-428f-b419-37ab655ffa0d)

![Image](https://github.com/user-attachments/assets/3d9a8f6c-2968-4bff-8460-af3c70456a9e)

**Comment by zkep** [comment]
> OK， 谢谢大佬支持
> 
> 还有就是一个需求，课程「**生成在线文档**」的时候，是否可以把文章评论也附带上去呢
> 
> ![Image](https://github.com/user-attachments/assets/38423fa6-212a-428f-b419-37ab655ffa0d)
> 
> ![Image](https://github.com/user-attachments/assets/3d9a8f6c-2968-4bff-8460-af3c70456a9e)

👌 安排，不过没那么快，估计得两三天

**Comment by zkep** [comment]
@springandme 已经修复了单个章节缓存，使用最新docker镜像即可

**Comment by springandme** [comment]
> [@springandme](https://github.com/springandme) 已经修复了单个章节缓存，使用最新docker镜像即可

好的，谢谢大佬

**Comment by zkep** [comment]
> > [@springandme](https://github.com/springandme) 已经修复了单个章节缓存，使用最新docker镜像即可
> 
> 好的，谢谢大佬

已经支持了，需要使用最新的镜像，重新生成在线文档

![Image](https://github.com/user-attachments/assets/24ae2962-93eb-4675-bab2-e02a2d0d72a6)

![Image](https://github.com/user-attachments/assets/6e2a03c6-f2bd-4264-8f92-3a1362c37a5c)

**Comment by zkep** [comment]
@springandme 
目前可以通过服务端配置文件 代理去请求极客时间的 图片资源，
解决 http refer 导致的裂图，图片不显示问题
就是流量需要从自己服务器走，如果是本地部署没问题，
如果在线部署要慎重
docker/server/config.yml
```yaml
site:
  download: true
  register:
    type: name # email | name | none
    email:
      subject: "我的极客时间邮箱验证码"
      body: "验证码： <b>%s</b> <br/><br/>"
      attach:
  login:
    type: name # email | name
    guest:
      name:
      password:
  play:
    type: origin  #  origin | local
    proxy_url:
      - https://res001.geekbang.org
      # - https://media001.geekbang.org
  proxy:  # 使用服务端代理请求极客时间图片资源，解决http refer限制 
    cache: true
    proxy_url: http://127.0.0.1:8090/v2/file/proxy?url={url}
    urls:     # 针对那些链接做服务端代理请求
      - https://static001.geekbang.org/resource/image
      - https://static001.geekbang.org/account/avatar
```
